### ISSUE TITLE
Does it not work while using the newest tensorflow?

### ISSUE THREAD

**Issue by LCLL** [buriburisuri/sugartensor#10]
It seems that it doesn't work when using the newest tensorflow.

As to the MNIST sample:

Traceback (most recent call last):
  File "test.py", line 18, in <module>
    loss = logit.sg_ce(target=y)
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_main.py", line 151, in wrapper
    out = func(tensor, tf.sg_opt(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_loss.py", line 44, in sg_ce
    out = tf.identity(tf.nn.sparse_softmax_cross_entropy_with_logits(tensor, opt.target), 'ce')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1684, in sparse_softmax_cross_entropy_with_logits
    labels, logits)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1533, in _ensure_xent_args
    "named arguments (labels=..., logits=..., ...)" % name)
ValueError: Only call `sparse_softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

**Comment by buriburisuri** [comment]
@LCLL Thanks for your information.  I'll check this on newest tensorflow.
