### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by chanil1218** [buriburisuri/sugartensor#4]
Sugartensor is not compatible with Python 3(in my case, Python 3.5.2).
Is there way to use sugartensor with Python 3?

**Comment by buriburisuri** [comment]
I have the plan to add some features in Dec.

1. Document
2. Python 3 support.
3. Docker support.

Sorry but you need python 2.7 interpreter now.

**Comment by buriburisuri** [comment]
@chanil1218 

Now, we support python3 at sugartensor v0.0.2.1.

**Comment by chanil1218** [comment]
That's nice. Thank you for your efforts!
2016년 12월 6일 (화) 오후 2:17, Namju Kim <notifications@github.com>님이 작성:

**Comment by nikparth** [comment]
I still have compatability issues with python3. Installing sugartensor 0.0.2.3 with tensorflow 0.12 I get the following error: 
~~~
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    .sg_periodic_shuffle(factor=2))
  File "/home/vision/anaconda3.5/lib/python3.5/site-packages/sugartensor/sg_main.py", line 151, in wrapper
    out = func(tensor, tf.sg_opt(kwargs))
  File "/home/vision/anaconda3.5/lib/python3.5/site-packages/sugartensor/sg_transform.py", line 556, in sg_periodic_shuffle
    for i in range(channel_target):
TypeError: 'float' object cannot be interpreted as an integer
~~~

I assume this has to do with the division in python 3 returning floats.

**Comment by LukasMosser** [comment]
Yes, that's correct. @buriburisuri pointed this out in another issue. Should be fixed soon. Maybe add a  Pr?

**Comment by buriburisuri** [comment]
@nikparth I've patched this at ver 0.0.2.4. Sorry for late reply.
