### ISSUE TITLE
AttributeError: 'FuncQueueRunner' object has no attribute '_runs'

### ISSUE THREAD

**Issue by wandering007** [buriburisuri/sugartensor#6]
Got errors when training:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_queue.py", line 108, in _run
    self._runs -= 1
AttributeError: 'FuncQueueRunner' object has no attribute '_runs'
```

**Comment by buriburisuri** [comment]
@wandering007  fixed from ver 0.0.2.1
